# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Knee Jar
email:  Jacob@kneejar.com
description: Personal Webpage of J.H
baseurl: "" # the subpath of your site, e.g. /blog
url: "www.kneejar.com" # the base hostname & protocol for your site
twitter_username: jxhaze
github_username:  haye8277
fingerprint:  F7E1 85CD 1CA0 4B63 5721  6B0B 4127 D2E8 792F 3A83
pgpkey: http://pgp.mit.edu/pks/lookup?op=get&search=0x4127D2E8792F3A83
# Build settings
markdown: kramdown
